Supervisord should start before supervisorctl.
In some instances, supervisord::reload was triggering before
the supervisord service had been spun up, causing the following
errors:

Info: Class[Supervisord::Reload]: Scheduling refresh of Exec[supervisorctl_reread]
Info: Class[Supervisord::Reload]: Scheduling refresh of Exec[supervisorctl_update]
Debug: Exec[supervisorctl_reread](provider=posix): Executing '/usr/local/bin/supervisorctl reread'
Debug: Executing '/usr/local/bin/supervisorctl reread'
Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]/returns: error: <class 'socket.error'>, [Errno 111] Connection refused: file: /usr/lib/python2.7/socket.py line: 571
Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]: Failed to call refresh: /usr/local/bin/supervisorctl reread returned 2 instead of one of [0]
Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]: /usr/local/bin/supervisorctl reread returned 2 instead of one of [0]
Debug: Exec[supervisorctl_update](provider=posix): Executing '/usr/local/bin/supervisorctl update'
Debug: Executing '/usr/local/bin/supervisorctl update'
Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]/returns: error: <class 'socket.error'>, [Errno 111] Connection refused: file: /usr/lib/python2.7/socket.py line: 571
Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]: Failed to call refresh: /usr/local/bin/supervisorctl update returned 2 instead of one of [0]
Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]: /usr/local/bin/supervisorctl update returned 2 instead of one of [0]